version: '2'
services:
  geth:
    image: ethereum/client-go
    command: --dev --datadir=/root/files --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain='*' --networkid=1234 --rpc --rpcaddr="0.0.0.0" init=/root/files/genesis.json --mine --nodiscover 
    volumes:
      - ../files:/root/files
      - ../files/password:/root/files/password:ro
      - ../files/genesis.json:/root/files/genesis.json:ro
      - ../files/keystore:/root/files/keystore:rw

    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
